.TH "Communicator.h" 3 "Thu Nov 29 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Communicator.h
.SH SYNOPSIS
.br
.PP
\fC#include <Windows\&.h>\fP
.br
\fC#include <tchar\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommunicator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
