.TH "DataCollector.h" 3 "Thu Nov 29 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataCollector.h
.SH SYNOPSIS
.br
.PP
\fC#include <myo/myo\&.hpp>\fP
.br
\fC#include <array>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataCollector\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
