.TH "Myo.cpp" 3 "Thu Nov 29 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Myo.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <myo/myo\&.hpp>\fP
.br
\fC#include 'DataCollector\&.h'\fP
.br
\fC#include 'Communicator\&.h'\fP
.br
\fC#include 'PeakDetector\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_USE_MATH_DEFINES\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr auto \fBConnected\fP = true"
.br
.ti -1c
.RI "const char \fBfilename\fP [] = 'test\&.txt '"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _USE_MATH_DEFINES"

.PP
Definition at line 1 of file Myo\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 20 of file Myo\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "constexpr auto Connected = true"

.PP
Definition at line 17 of file Myo\&.cpp\&.
.SS "const char filename[] = 'test\&.txt '"

.PP
Definition at line 18 of file Myo\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
