.TH "PeakDetector.cpp" 3 "Thu Nov 29 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeakDetector.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'PeakDetector\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
