.TH "PeakDetector.h" 3 "Thu Nov 29 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeakDetector.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPeakDetector< T >\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPeakType\fP : uint8_t { \fBpositive\fP, \fBnegative\fP, \fBnoneDetected\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPeakType\fP : uint8_t"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIpositive \fP\fP
.TP
\fB\fInegative \fP\fP
.TP
\fB\fInoneDetected \fP\fP
.PP
Definition at line 15 of file PeakDetector\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
